### ISSUE TITLE
Not all parameter changes getting tracked in scenairo B

### ISSUE THREAD

**Issue by jlessler** [HopkinsIDD/ConTESSA#1]
Take the parameters from the Shire default scenario then create a scenario B with the following changes:
- S.2.1 set to 66%
- All delays set to 14 days (S6, H3, C3). 

Note we still get substantial R0 reduction.

Create a scenario A with same parameters. Note there is no R0 reduction.

**Comment by kgrantz** [comment]
noting that this is due to t_q issues - we want to remove t_q advanced option and revert to t_q and omega_q as weighted average of community + household contact parameters

**Comment by LucyMcGowan** [comment]
should be resolved now :+1:
