### ISSUE TITLE
advanced option settings for scenario B don't match scenario A

### ISSUE THREAD

**Issue by kgrantz** [HopkinsIDD/ConTESSA#10]
If changing Scenario A advanced options, and then choosing to specify Scenario B, the Scenario B default advanced options do not match Scenario A. Particularly problematic for R0 - because the top display for R on the Dashboard will show [ScenarioA_R0] -> [ScenarioB_R], but [ScenarioB_R] is calculated from [ScenarioB_R0], which defaults to 2.5.

**Comment by LucyMcGowan** [comment]
I think what you are saying is the default values from Scenario B advanced options should always be the same as Scenario A when they first come up? I can definitely do this! I'm not sure what you mean by [ScenarioB_R] is calculated from [ScenarioB_R0], which defaults to 2.5, I think [Scenario B_R] works as expected that it is calculated based on whatever the advanced option inputs are?

**Comment by kgrantz** [comment]
Yes, it calculates ScenarioB_R from the advanced option input for Scenario B (which is correct!) - the issue is that the top display shows that the value has changed from ScenarioA_R0 to ScenarioB_R, when scenarioA_R0 does not necessarily equal scenarioB_R0
e.g., I changed scenario A R0 to 3, but scenario B R0 defaulted to 2.5. The top bar showed that scenario B changed R0 from 3 -> 2.4

**Comment by LucyMcGowan** [comment]
OH 😱 that is not good either way the 3 should be a 2.5. Pushing a fix for both now 👍
