### ISSUE TITLE
ConTESSA Sliders Out of Order

### ISSUE THREAD

**Issue by smnaing** [HopkinsIDD/ConTESSA#17]
Hi, I am attempting to use the sliders on ConTESSA and some of them are not working (i.e., some of the sliders are not showing up - just the text associated with them). This issue is present among the following sliders: S5, S6, H3, C3.

Thank you

**Comment by LucyMcGowan** [comment]
Thank you for letting us know! I believe this should be resolved (a package was updated in the past week and needed to be updated on the server)

Working for me now:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/8431897/112053340-9e8f2280-8b2a-11eb-86d7-45c2910ace60.png">

Please re-open if it is still not working for you.
