### ISSUE TITLE
fix differences between sym/asym delays in reports

### ISSUE THREAD

**Issue by kgrantz** [HopkinsIDD/ConTESSA#2]
should use t_qha = t_pa + (t_qhs - t_ps) in place of t_qha = t_qhs. 

Repeat for t_pa/t_ps, t_qha/t_qhs, t_qca/t_qcs

**Comment by LucyMcGowan** [comment]
Here’s how I do it in the server starting here: https://github.com/HopkinsIDD/ConTESSA/blob/f07f15c7e416ff44d3d62804ff858fe54cff2b12/server.R#L1724-L1771
