### ISSUE TITLE
Intermittent download errors due to "Server problem"

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/ConTESSA#5]
Seems to be most prevalent on Edge and for the reports (both PDF and Word versions)

**Comment by kgrantz** [comment]
working on this - at least for the scenario B version we’re aware there were issues preventing reports from being generated and downloaded. Were there issues with the single scenario reports too?

**Comment by LucyMcGowan** [comment]
@eclee25 Do you still see this happening after Kyra's updates? Trying to see if this is related to #4 or something different.

**Comment by eclee25** [comment]
I haven't encountered any of these issues recently @LucyMcGowan but will test throughout the day

**Comment by LucyMcGowan** [comment]
I'm going to close this for now since we haven't seen it recently, happy to reopen if it comes up again!
