### ISSUE TITLE
Server state doesn't save

### ISSUE THREAD

**Issue by LucyMcGowan** [HopkinsIDD/ConTESSA#8]
The URL encoding doesn't seem to work on the RStudio Connect Server

**Comment by kgrantz** [comment]
URL encoding works for me now. Can use back arrow + copy/paste URL to create same scenario in new browser. @LucyMcGowan do you want to confirm?

**Comment by LucyMcGowan** [comment]
Ah yes, meant to close! It’s been fixed 🎉
